
import { AckSchemaType, FieldDefinition } from './ack-schema';

export const MrxSchema: AckSchemaType = {
    header: [
        { name: 'Record Type', start: 1, end: 1, length: 1, type: 'Alpha', expectedValue: 'H', description: 'Valid Value: H=Header' },
        { name: 'Sender Code', start: 2, end: 26, length: 25, type: 'AlphaNumeric', expectedValue: 'BCBSMN', description: 'Value = BCBSMN' },
        { name: 'Run Date', start: 27, end: 34, length: 8, type: 'Numeric', description: 'CCYYMMDD' },
        { name: 'Original File Name', start: 35, end: 79, length: 45, type: 'AlphaNumeric', description: 'BCBSMN_PRIME_CLAIMS_ccyymmddhhmmss.txt' },
        { name: 'Filler', start: 80, end: 921, length: 842, type: 'AlphaNumeric', description: 'blank Fill' },
    ],
    data: [
        { name: 'Record Type', start: 1, end: 1, length: 1, type: 'Alpha', expectedValue: 'D', description: 'Valid Value: D=Data' },
        { name: 'Line of Business Identifier', start: 2, end: 11, length: 10, type: 'AlphaNumeric', description: 'blank Fill' },
        { name: 'Sender Claim Number', start: 12, end: 31, length: 20, type: 'AlphaNumeric', description: 'Claim will be rejected if claim number is missing' },
        { name: 'Claim Line Number', start: 32, end: 36, length: 5, type: 'Numeric', description: 'Examples: 00001, 00010, 00100' },
        { name: 'Member ID', start: 37, end: 66, length: 30, type: 'AlphaNumeric', description: 'Must match Member ID on Eligibility file' },
        { name: 'Patient ID', start: 67, end: 104, length: 38, type: 'AlphaNumeric', description: 'Populate if present' },
        { name: 'Patient First Name', start: 105, end: 119, length: 15, type: 'AlphaNumeric', description: 'Claim will be rejected if missing' },
        { name: 'Patient Middle Name', start: 120, end: 134, length: 15, type: 'AlphaNumeric', description: 'Populate if present' },
        { name: 'Patient Last Name', start: 135, end: 159, length: 25, type: 'AlphaNumeric', description: 'Claim will be rejected if missing' },
        { name: 'Patient Address 1', start: 160, end: 195, length: 36, type: 'AlphaNumeric', description: 'Populate if present' },
        { name: 'Patient Address 2', start: 196, end: 231, length: 36, type: 'AlphaNumeric', description: 'Populate if present' },
        { name: 'Patient City', start: 232, end: 255, length: 24, type: 'AlphaNumeric', description: 'Populate if present' },
        { name: 'Patient State', start: 256, end: 257, length: 2, type: 'Alpha', description: 'Populate if present' },
        { name: 'Patient Zip', start: 258, end: 267, length: 10, type: 'AlphaNumeric', description: 'Populate if present' },
        { name: 'Patient Date of Birth', start: 268, end: 275, length: 8, type: 'Numeric', description: 'CCYYMMDD' },
        { name: 'Patient Gender', start: 276, end: 276, length: 1, type: 'Alpha', description: 'F=Female, M=Male, U=Unknown' },
        { name: 'Relationship To Insured', start: 277, end: 277, length: 1, type: 'Alpha', description: 'C=Child, M=Member, S=Spouse' },
        { name: 'Primary Coverage Indicator', start: 278, end: 278, length: 1, type: 'Alpha', description: 'Y=Yes (COB), N=No' },
        { name: 'Provider Tax ID Number', start: 279, end: 288, length: 10, type: 'AlphaNumeric', description: 'Claim will be rejected if missing' },
        { name: 'Rendering Provider Name', start: 289, end: 324, length: 36, type: 'AlphaNumeric', description: 'Format: Lastname, Firstname Middlename' },
        { name: 'Rendering Provider Address 1', start: 325, end: 360, length: 36, type: 'AlphaNumeric', description: 'Provider Address must be on the claim' },
        { name: 'Rendering Provider City', start: 397, end: 420, length: 24, type: 'AlphaNumeric', description: 'Provider City must be on the claim' },
        { name: 'Rendering Provider State', start: 421, end: 422, length: 2, type: 'Alpha', description: 'Provider State must be on the claim' },
        { name: 'Rendering Provider NPI #', start: 433, end: 444, length: 12, type: 'AlphaNumeric', description: "Rendering provider's National Provider Identifier" },
        { name: 'Rendering Provider Par Status', start: 445, end: 445, length: 1, type: 'Alpha', description: 'P=Par, N=Nonpar' },
        { name: 'Pay To Provider Name', start: 446, end: 481, length: 36, type: 'AlphaNumeric', description: 'Populate with same info if Rendering/Pay To are same' },
        { name: 'Claim Received Date', start: 602, end: 609, length: 8, type: 'Numeric', description: 'CCYYMMDD' },
        { name: 'Service Date From', start: 610, end: 617, length: 8, type: 'Numeric', description: 'CCYYMMDD' },
        { name: 'Place of Service', start: 626, end: 627, length: 2, type: 'AlphaNumeric', description: 'Line level Place of Service' },
        { name: 'Diagnosis 1', start: 632, end: 641, length: 10, type: 'AlphaNumeric', description: 'Strip decimals prior to submitting' },
        { name: 'Procedure Code', start: 672, end: 679, length: 8, type: 'AlphaNumeric', description: 'Codes less than 5 characters assumed Revenue codes' },
        { name: 'Units/Quantity', start: 688, end: 696, length: 9, type: 'Numeric', description: 'Partial Units will be rounded up' },
        { name: 'NDC', start: 697, end: 711, length: 15, type: 'AlphaNumeric', description: 'National Drug Code; strip all dashes' },
        { name: 'Billed Amount', start: 729, end: 737, length: 9, type: 'Numeric', description: "Format '000050000' for $500.00" },
        { name: 'Allowed Amount', start: 738, end: 746, length: 9, type: 'Numeric', description: 'Amount for all units, not per unit' },
        { name: 'Client Denial Codes', start: 748, end: 767, length: 20, type: 'AlphaNumeric', description: 'Required when MRx needs to ignore denied lines' },
        { name: 'Adjustment Identifier', start: 768, end: 768, length: 1, type: 'AlphaNumeric', description: 'A=Original, J=Adjustment, V=Void, R=Replacement' },
        { name: 'Original Claim Number', start: 769, end: 783, length: 15, type: 'AlphaNumeric', description: "Required if Adjustment ID is 'J', 'V', or 'R'" },
    ],
    trailer: [
        { name: 'Record Type', start: 1, end: 1, length: 1, type: 'Alpha', expectedValue: 'T', description: 'Valid Value: T = Trailer Record' },
        { name: 'Total Records', start: 2, end: 21, length: 20, type: 'Numeric', description: 'Total # of claim records sent in file' },
        { name: 'Total Claims', start: 22, end: 41, length: 20, type: 'Numeric', description: 'Total # of claims sent in file' },
        { name: 'Sender Code', start: 42, end: 66, length: 25, type: 'AlphaNumeric', expectedValue: 'BCBSMN', description: 'Value = BCBSMN' },
        { name: 'Filler', start: 67, end: 921, length: 855, type: 'AlphaNumeric', description: 'blank Fill' },
    ]
};
