import { AckSchemaType } from './ack-schema';

export const RespSchema: AckSchemaType = {
    header: [
        { name: 'Record Type', start: 1, end: 1, length: 1, type: 'Alpha', expectedValue: 'H', description: "Valid Value: 'H'=Header" },
        { name: "'PRIME' Alpha", start: 2, end: 6, length: 5, type: 'Alpha', expectedValue: 'PRIME', description: "Valid Value: 'PRIME'" },
        { name: 'Receiver ID', start: 7, end: 31, length: 25, type: 'AlphaNumeric', expectedValue: 'BCBSMN', description: "Valid Value: 'CUSTOMER'" },
        { name: 'Creation Date', start: 32, end: 39, length: 8, type: 'Numeric', description: 'CCYYMMDD' },
        { name: 'Selection From Date', start: 40, end: 47, length: 8, type: 'Numeric', description: 'CCYYMMDD' },
        { name: 'Selection To Date', start: 48, end: 55, length: 8, type: 'Numeric', description: 'Populate with same date as Selection From Date' },
        { name: 'Filler A/N', start: 56, end: 230, length: 175, type: 'AlphaNumeric', description: 'blank fill' },
    ],
    data: [
        { name: 'Record Type', start: 1, end: 1, length: 1, type: 'Alpha', expectedValue: 'D', description: "Valid Value: 'D'=Data" },
        { name: 'Claim Number', start: 2, end: 21, length: 20, type: 'AlphaNumeric', description: 'Client submitted Claim Number' },
        { name: 'Claim Line Number', start: 22, end: 26, length: 5, type: 'Numeric', description: 'Client submitted Claim Line Number' },
        { name: 'Member ID', start: 27, end: 56, length: 30, type: 'AlphaNumeric', description: 'Client submitted Member ID' },
        { name: 'Patient ID', start: 57, end: 94, length: 38, type: 'AlphaNumeric', description: 'Client submitted Patient ID (if received on inbound file)' },
        { name: 'Provider NPI', start: 95, end: 106, length: 12, type: 'Numeric', description: 'Client submitted Pay to Provider NPI (if received on inbound file)' },
        { name: 'Provider TIN', start: 107, end: 115, length: 9, type: 'Numeric', description: 'Client submitted Pay to Provider TIN' },
        { name: 'MRx Claim Number', start: 116, end: 127, length: 12, type: 'AlphaNumeric', description: 'MRx assigned Claim Number' },
        { name: 'MRx Claim Line Number', start: 128, end: 130, length: 3, type: 'Numeric', description: 'MRx assigned Claim Line Number' },
        { name: 'Allowed Amount', start: 131, end: 139, length: 9, type: 'Numeric', description: 'Populate with Allowed Amount' },
        { name: 'Units approved', start: 140, end: 148, length: 9, type: 'Numeric', description: 'Indicates the number of whole units MRx approved for this claim line' },
        { name: 'Units Denied', start: 149, end: 157, length: 9, type: 'Numeric', description: 'Indicates the number of whole units MRx denied for this claim line' },
        { name: 'MRx Claim Status', start: 158, end: 159, length: 2, type: 'Alpha', description: 'Valid Values: DY=Denied, PA= Partial Approval, PD=Paid' },
        { name: 'Denial Code', start: 160, end: 169, length: 10, type: 'AlphaNumeric', description: 'MRx denial code (or neutral code for claim lines not edited at MRx )' },
        { name: 'MRx Authorization Number', start: 170, end: 189, length: 20, type: 'AlphaNumeric', description: 'When applicable' },
        { name: 'Procedure Code', start: 190, end: 197, length: 8, type: 'AlphaNumeric', description: '' },
        { name: 'Response indicator', start: 198, end: 198, length: 1, type: 'AlphaNumeric', description: 'Valid: A=original claim, J=adj, R=replacement, C=adjustment request' },
        { name: 'ITS Indicator', start: 199, end: 199, length: 1, type: 'AlphaNumeric', description: 'Valid Values: Y=Yes, N=No' },
        { name: 'Filler A/N', start: 200, end: 200, length: 1, type: 'AlphaNumeric', description: '' },
        { name: 'SCCF # A/N', start: 201, end: 217, length: 17, type: 'AlphaNumeric', description: '' },
        { name: 'Adjustment reason', start: 218, end: 220, length: 3, type: 'AlphaNumeric', description: "Values: 'RAA' (Retro Auth Adj), 'CSA' (Claims Support Adj)" },
        { name: 'Client #', start: 221, end: 230, length: 10, type: 'AlphaNumeric', description: '' },
    ],
    trailer: [
        { name: 'Record Type', start: 1, end: 1, length: 1, type: 'Alpha', expectedValue: 'T', description: "Valid Value: 'T' = Trailer" },
        { name: 'Trailer A/N', start: 2, end: 8, length: 7, type: 'AlphaNumeric', expectedValue: 'TRAILER', description: "Valid Value: 'TRAILER'" },
        { name: 'Total Records', start: 9, end: 28, length: 20, type: 'Numeric', description: '' },
        { name: 'Filler', start: 29, end: 230, length: 202, type: 'AlphaNumeric', description: 'blank fill' },
    ]
};

export const RESP_DENIAL_CODES = [
    { code: 'GI', short: 'DENY-Procedure and DOS do not match auth', long: 'The procedure and the date of service do not match the authorization. Based on MRX/Prime guidelines, the claim has been denied.' },
    { code: 'GJ', short: 'DENY-Procedure code does not match auth', long: 'The procedure code does not match the authorization. Based on MRX/Prime guidelines, the claim has been denied.' },
    { code: 'IO', short: 'DENY-Patient has exceeded authorized number of visits', long: 'Patient has exceeded the authorized number of visits/days with this provider. Based on MRX/Prime guidelines, the claim has been denied.' },
    { code: 'IQ', short: 'DENY-Date of Service does not match authorized date span', long: 'The date of service was not provided within the authorized date span to this provider. Based on MRX/Prime guidelines, the claim has been denied.' },
    { code: '12', short: 'DENY-itemization needed', long: 'We are unable to process this claim because the information received is not sufficient for us to process this claim. Please submit an itemized bill identifying each date of service and/or procedure performed, and/or units billed on a separate line.' },
    { code: 'C3', short: 'DENY - duplicate prev submit and processed or still in process.', long: 'We are unable to process this claim because the same charges have already been processed or is still in process, therefore the claim is denied.' },
    { code: 'C5', short: 'DENY-units per day exceed amount allowable', long: 'We are unable to process this claim because the charges exceed the maximum units allowed per day. The charges over the maximum have been denied.' },
    { code: '42', short: 'DENY-Clinical Dept denial (Pre Service)', long: 'We are unable to process this claim because the dates of service were already reviewed by our Clinical Management department and a non authorization letter was sent to the ordering physician. Therefore the claim is denied.' },
    { code: '43', short: 'DENY-Clinical Dept denial (Post Service)', long: 'We are unable to process this claim because the dates of service were already reviewed by our Clinical Management department... (Post Service)' },
    { code: 'C6', short: 'DENY-units exceed amount allowable for time period', long: 'We are unable to process this claim because the patient has reached the maximum number of units for this condition and the claim is denied.' },
    { code: 'E8', short: 'DENY- Patient not eligible.', long: 'We are unable to process this claim because the member is not eligible for coverage on this date of service. The claim should be submitted to the insurance carrier or plan under which the member was eligible on the date services were rendered.' },
    { code: 'EB', short: 'DENY-OCE-dx/age conflict', long: 'We are unable to process this claim because the diagnosis code billed is inconsistent for the patient\'s age. This claim has been denied based on the Centers for Medicare and Medicaid Services (CMS) Outpatient Prospective Payment System (OPPS) payment rules. Applies to Medicare only.' },
    { code: 'G3', short: 'DENY-DX not eligible for code', long: 'We are unable to process this claim because the diagnosis code billed is not appropriate for the patient\'s treatment. Therefore the claim is denied.' },
    { code: 'J7', short: 'DENY--requested info not recd', long: 'We are unable to process this claim because we previously requested additional information to determine the medical necessity of this service. To date, we have not received a response, therefore the claim is denied.' },
    { code: 'MV', short: 'DENY-DX not appropriate for drug billed', long: 'The procedure code and modifier submitted is not appropriate for the treatment of the diagnosis billed.' },
    { code: 'F9', short: 'DENY-PAR PROV-No auth on file.', long: 'We are unable to process this claim because there is no authorization for this date of service with this participating provider. Therefore the claim is denied. The member is only responsible for the co-pay and/or co-insurance. Provider must not balance bill the member.' },
    { code: 'I2', short: 'DENY-units exceed amount allowable for time period w/in auth', long: 'We are unable to process this claim because the patient has reached the maximum authorized number of units for this condition and the claim is denied.' },
    { code: 'IV', short: 'DENY-units per day exceed amount allowable within auth', long: 'We are unable to process this claim because the charges exceed the maximum authorized units allowed per day. The charges over the maximum have been denied.' },
];
