
export const ACK_DENIAL_CODES = [
    { code: 'EDI3108', short: 'Reject to client - Client\'s Claim Number Not on File' },
    { code: 'EDI3119', short: 'Reject to client - Duplicate Claim # Submitted' },
    { code: 'EDI3130', short: 'Reject to client - Duplicate claim/line' },
    { code: 'EDI3188', short: 'Reject to client - Client\'s Claim Line Number Missing' },
    { code: 'EDI3107', short: 'Reject to client - Claim\'s DOS Prior to Client\'s Contracted Start Date' },
    { code: 'EDI1300', short: 'Reject to client - The Service From Date is Invalid' },
    { code: 'EDI1310', short: 'Reject to client - The Service To Date is Invalid' },
    { code: 'EDI1330', short: 'Reject to client - The Service From/To Date is after the Received Date' },
    { code: 'EDI3136', short: 'Reject to client - Client received date missing or invalid' },
    { code: 'EDI3121', short: 'Reject to client - Member ID Missing' },
    { code: 'EDI3122', short: 'Reject to client - Patient Name Missing' },
    { code: 'EDI3123', short: 'Reject to client - Patient DOB Missing' },
    { code: 'EDI3124', short: 'Reject to client - TIN Missing' },
    { code: 'EDI3132', short: 'Reject to client - Diagnosis Code Missing' },
    { code: 'EDI3109', short: 'Reject to client - non-covered Place of Service' },
    { code: 'EDI3126', short: 'Reject to client - non-Covered Type of Bill' },
    { code: 'EDI3110', short: 'Reject to client - non-covered Procedure Code' },
    { code: 'EDI3120', short: 'Reject to client - Line Item Service Unit Count equals zero' },
    { code: 'EDI3115', short: 'Reject to client - Line Item Charge Amount not received' },
    { code: 'EDI3118', short: 'Reject to client - Allowed Amount is Greater than Billed Amt' },
    { code: 'EDI3129', short: 'Reject to client - Line of Business missing or not contracted' },
    { code: 'EDI3133', short: 'Reject to client - Client Claim Status Missing' },
];

export const RESP_DENIAL_CODES = [
    { code: 'GI', short: 'DENY-Procedure and DOS do not match auth', long: 'The procedure and the date of service do not match the authorization. Based on MRX/Prime guidelines, the claim has been denied.' },
    { code: 'GJ', short: 'DENY-Procedure code does not match auth', long: 'The procedure code does not match the authorization. Based on MRX/Prime guidelines, the claim has been denied.' },
    { code: 'IO', short: 'DENY-Patient has exceeded authorized number of visits', long: 'Patient has exceeded the authorized number of visits/days with this provider. Based on MRX/Prime guidelines, the claim has been denied.' },
    { code: 'IQ', short: 'DENY-Date of Service does not match authorized date span', long: 'The date of service was not provided within the authorized date span to this provider. Based on MRX/Prime guidelines, the claim has been denied.' },
    { code: '12', short: 'DENY-itemization needed', long: 'We are unable to process this claim because the information received is not sufficient for us to process this claim. Please submit an itemized bill identifying each date of service and/or procedure performed, and/or units billed on a separate line.' },
    { code: 'C3', short: 'DENY - duplicate prev submit and processed or still in process.', long: 'We are unable to process this claim because the same charges have already been processed or is still in process, therefore the claim is denied.' },
    { code: 'C5', short: 'DENY-units per day exceed amount allowable', long: 'We are unable to process this claim because the charges exceed the maximum units allowed per day. The charges over the maximum have been denied.' },
    { code: '42', short: 'DENY-Clinical Dept denial (Pre Service)', long: 'We are unable to process this claim because the dates of service were already reviewed by our Clinical Management department and a non authorization letter was sent to the ordering physician. Therefore the claim is denied.' },
    { code: '43', short: 'DENY-Clinical Dept denial (Post Service)', long: 'We are unable to process this claim because the dates of service were already reviewed by our Clinical Management department... (Post Service)' },
    { code: 'C6', short: 'DENY-units exceed amount allowable for time period', long: 'We are unable to process this claim because the patient has reached the maximum number of units for this condition and the claim is denied.' },
    { code: 'E8', short: 'DENY- Patient not eligible.', long: 'We are unable to process this claim because the member is not eligible for coverage on this date of service. The claim should be submitted to the insurance carrier or plan under which the member was eligible on the date services were rendered.' },
    { code: 'EB', short: 'DENY-OCE-dx/age conflict', long: 'We are unable to process this claim because the diagnosis code billed is inconsistent for the patient\'s age. This claim has been denied based on the Centers for Medicare and Medicaid Services (CMS) Outpatient Prospective Payment System (OPPS) payment rules. Applies to Medicare only.' },
    { code: 'G3', short: 'DENY-DX not eligible for code', long: 'We are unable to process this claim because the diagnosis code billed is not appropriate for the patient\'s treatment. Therefore the claim is denied.' },
    { code: 'J7', short: 'DENY--requested info not recd', long: 'We are unable to process this claim because we previously requested additional information to determine the medical necessity of this service. To date, we have not received a response, therefore the claim is denied.' },
    { code: 'MV', short: 'DENY-DX not appropriate for drug billed', long: 'The procedure code and modifier submitted is not appropriate for the treatment of the diagnosis billed.' },
    { code: 'F9', short: 'DENY-PAR PROV-No auth on file.', long: 'We are unable to process this claim because there is no authorization for this date of service with this participating provider. Therefore the claim is denied. The member is only responsible for the co-pay and/or co-insurance. Provider must not balance bill the member.' },
    { code: 'I2', short: 'DENY-units exceed amount allowable for time period w/in auth', long: 'We are unable to process this claim because the patient has reached the maximum authorized number of units for this condition and the claim is denied.' },
    { code: 'IV', short: 'DENY-units per day exceed amount allowable within auth', long: 'We are unable to process this claim because the charges exceed the maximum authorized units allowed per day. The charges over the maximum have been denied.' },
];
